---
name: addlicense

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions:
  contents: read

jobs:
  addlicense:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v5

      - name: Pull contianer for addlicense
        run: docker pull ghcr.io/google/addlicense:latest

      - name: invoke addlicense
        run: docker run -it -v ${PWD}:/src ghcr.io/google/addlicense -l "apache" -c "Google LLC" .

      - name: check if it worked
        run: ls && cat .github/workflows/addlicense.yaml

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
