---
name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions:
  contents: read

jobs:
  run-addlicense:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v5

      - name: Pull contianer for addlicense
        run: go install github.com/google/addlicense@latest

      - name: invoke addlicense
        run: addlicense -l "apache" -c "Google LLC" .
