name: Add License

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  add-license:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull Addlicense Docker image
        run: docker pull ghcr.io/google/addlicense:latest

      - name: Run Addlicense
        run: |
          docker run -v $(pwd):/github/workspace ghcr.io/google/addlicense:latest \
            -f apache \
            -c "Google LLC" \
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
