name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - run: pip install pyproject.toml
    - run: pip install -r reqs/requirements_all.txt
#    - uses: yezz123/setup-uv@v4
#
#    - uses: cloudposse/github-action-pre-commit@v2.1.2
