name: "CI - terraform validate"

    on: [push, pull_request]

    jobs:
      terraform:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3
          - name: Terraform Init
            working-directory: sample-deployments/composer-orchestrated-process
            run: terraform init
          - name: Terraform validate
            working-directory: terraform
            run: terraform validate
